site_name: Spring Notes
site_url: http://spring.zayedbinhasan.me/
repo_url: https://github.com/frost23z/spring-notes

theme:
  name: material
  logo: 'media/icon/logo.png'
  favicon: 'media/icon/logo.png'
  icon:
    admonition:
      info: octicons/alert-24
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode- exceptions.md

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.copy
    - content.code.annotate 

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight: # allows code highlighting
      anchor_linenums: true # adds line numbers to code blocks
      line_spans: __span # adds line spans to code blocks
      pygments_lang_class: true # adds language class to code blocks
  - pymdownx.inlinehilite # allows inline code highlighting
  - pymdownx.snippets # allows code snippets